name: supabase-backup
on:
  schedule:
    - cron: "17 2 * * *"   # daily at 02:17 UTC
  workflow_dispatch: {}
jobs:
  backup:
    if: ${{ secrets.SUPABASE_DB_URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dump database
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          mkdir -p backups
          TS=$(date -u +"%Y%m%dT%H%M%SZ")
          pg_dump --no-owner --no-privileges --format=custom "$SUPABASE_DB_URL" -f "backups/zuvo1_$TS.dump"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-db-backup
          path: backups/*.dump
          retention-days: 14
